# Generated by Django 5.2.6 on 2025-10-29 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_chatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(default='My Bot', max_length=100)),
                ('color', models.CharField(default='#000000', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
